version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
environment:
  PackageVersion: $(appveyor_build_version)
build_script:
  - cmd: msbuild ".\build\build.proj" /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:PackageVersion=$(appveyor_build_version)
before_build:
  - nuget restore
artifacts:
  - path: '**\*.nupkg'
    name: Nuget packages
